### ISSUE TITLE
Wrong decision

### ISSUE THREAD

**Issue by mika-f** [fuyuno/Norma#11]
CM 放送中出ない時にも、まれに CM と判定されることがある。

**Comment by EpgTimerWeb** [comment]
CM視聴中のAPI呼び出しで検出することができたりします

**Comment by mika-f** [comment]
@EpgTimerWeb CM 視聴中かどうかの API があったのですね。
それで検出してみるようにしてみます。

**Comment by EpgTimerWeb** [comment]
正確にはCM視聴中に視聴中であることを伝えるAPIが呼ばれているのでそこをフックできれば検出できると思います。
`https://media.abema.io/tracks/glasgow/:channelId/:sequence/:elapsedTime/:duration`

**Comment by EpgTimerWeb** [comment]
まあ、それこそ完璧を求めるなら自前のプレイヤーのせるしかないですし。
ある程度できればいいかと

**Comment by mika-f** [comment]
そうですね。
とりあえず、番組再生中にもかかわらず、 CM と判定されている部分だけ直せるようやってみます。

**Comment by mika-f** [comment]
'16/05/24 に落ちて以降、ひどくなってて辛い。

**Comment by mika-f** [comment]
諦め。

**Comment by EpgTimerWeb** [comment]
RequestHandlerでmain.jsを書き換えるとか
h=t.isPg

**Comment by mika-f** [comment]
AbemaTV 自体の CM 判定がアレだし、 CM 中もコメントできるらしいし、もうロックしなくてもいいかなと...
