### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by mika-f** [fuyuno/Norma#12]
番組表を実装
通常の TV と同じく、一週間分見ることができればいいかも。
- [x] 番組表
- [x] 視聴予約
  - [x] 単体予約
  - [x] 時間予約
  - [x] キーワード予約(通常, 正規表現)
- [x] 詳細表示

**Comment by mika-f** [comment]
あと視聴予約

**Comment by EpgTimerWeb** [comment]
EDCBなどを参考にしてみては？

**Comment by mika-f** [comment]
便利そうですね。
参考にしてみます。

**Comment by mika-f** [comment]
こんなもんだろうという。
あとは詳細表示などかしら。
<img width="675" alt="default" src="https://cloud.githubusercontent.com/assets/10832834/15449786/dae2debc-1fc2-11e6-90c2-1d7eed17c4ff.PNG">

**Comment by mika-f** [comment]
メモリリーク起こしてる。
https://github.com/fuyuno/Norma/blob/95685c52d173a92dc80281c36f6a5f7998e334ab/Norma/Views/TimetableWindow.xaml#L193-L195

**Comment by mika-f** [comment]
予約付近のレイアウトが思い浮かばない
(下のスペースに置きたい)
<img width="450" alt="default" src="https://cloud.githubusercontent.com/assets/10832834/15563776/fbbc9722-2346-11e6-9038-b2c464573707.PNG">

**Comment by mika-f** [comment]
<img width="450" alt="default" src="https://cloud.githubusercontent.com/assets/10832834/15626953/3df7d18c-250f-11e6-8c81-0fd884e1f644.PNG">
一般的な録画プレイヤーの、繰り返しのやつの種類がわからない…(週1でとかかな)
