### ISSUE TITLE
norma.exe

### ISSUE THREAD

**Issue by 888kk** [fuyuno/Norma#81]
Releases からVersion 2.0.0.228をダウンロードしたのですが、
Norma.exeが同梱されておらず起動できません。
zipとは別にダウンロードするのでしょうか？

**Comment by mika-f** [comment]
申し訳ありません。
現時点では、 Norma のビルド済みバイナリ (`~.exe` や `~.dll`) は配布しておりません。  
最新版をお使いいただく場合は、ご自身でビルドして頂く必要があります。  
過去のものでも良い場合は、 AppVeyor から取得可能です。
https://ci.appveyor.com/project/fuyuno/norma/history

ビルド方法については、以下の Wiki をご覧ください。
https://github.com/fuyuno/Norma/wiki/How-to-build
